spring:
  application:
    name: api-psicosocial

  # O Railway injeta o valor da porta na variável 'PORT'
  server:
    port: ${PORT:8080}

  data:
    mongodb:
      # Use ${MONGO_URL} se você usar o Add-on do MongoDB do Railway.
      # Se usar o MongoDB Atlas, você precisará adicionar uma variável 'MONGO_URL' (ou similar)
      # no painel do Railway e colocar a URI do Atlas lá.
      uri: ${MONGO_URL}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

jwt:
  # O segredo JWT DEVE ser injetado por uma variável de ambiente no Railway
  # para máxima segurança, mas mantemos o valor de fallback para desenvolvimento local.
  secret: ${JWT_SECRET:aMinhaChaveSecretaParaOProjetoDaSoriComPeloMenos32Caracteres}